# Generated by Django 5.1.7 on 2025-05-01 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
        ('ticket', '0004_rename_date_created_photo_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ticket.ticket'),
        ),
    ]
