# Generated by Django 5.1.7 on 2025-04-01 09:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Ticket',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
    ]
