# Generated by Django 5.2 on 2025-04-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_rename_blog_ticket_remove_photo_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
