# Generated by Django 5.1.7 on 2025-05-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date_created',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='date_created',
            new_name='time_created',
        ),
    ]
